# Generated by Django 4.2.7 on 2024-09-19 08:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0004_user_otp_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp_expiry',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 9, 19, 8, 28, 2, 650317, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
