# Generated by Django 4.2.7 on 2024-09-04 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_deliverycouriers_url_parameter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='digital',
            new_name='is_bestseller',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='featured',
            new_name='is_featured',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='hot_deal',
            new_name='is_new_arrival',
        ),
    ]
