# Generated by Django 4.2.7 on 2024-09-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='order',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
